- include: apt_stop.yml
  when: ansible_os_family == 'Debian'
  tags: stop

- include: yum_stop.yml
  when: ansible_os_family == 'RedHat'
  tags: stop

- include: windows_stop.yml
  when: ansible_os_family == 'Windows'
  tags: stop