---
- name: Check and create temp directory
  win_file:
    path: C:\{{ destination_dir }}
    state: directory

- name: Check if CloudPassage Halo agent is downloaded
  win_stat: path='C:\{{ destination_dir }}\cphalo-{{ halo_package_version }}-win64.exe'
  register: stat_file

- name: Download CloudPassage Halo agent installer
  win_get_url:
    url: 'https://production.packages.cloudpassage.com/windows/cphalo-{{ halo_package_version }}-win64.exe'
    dest: 'C:\{{ destination_dir }}\cphalo-{{ halo_package_version }}-win64.exe'
  when: stat_file.stat.exists == False

- name: check if make server label
  set_fact:
    azure_id: "/server-label={{ azure_id }}_{{ ansible_nodename }}"
  when: azure_id != None

- name: Install and run for the first time
  win_shell: '.\cphalo-{{ halo_package_version }}-win64.exe --% /S /agent-key={{ agent_key }} /grid="https://grid.cloudpassage.com/grid" {{ azure_id }}'
  args:
    chdir: C:\{{ destination_dir }}\

- name: remove installer
  win_shell: erase .\cphalo-{{ halo_package_version }}-win64.exe
  args:
    chdir: C:\{{ destination_dir }}\