---
- name: Download CloudPassage Halo agent installer
  win_get_url:
    url: 'https://production.packages.cloudpassage.com/windows/cphalo-{{ halo_package_version }}-win64.exe'
    dest: 'C:\{{ destination_dir }}\cphalo-{{ halo_package_version }}-win64.exe'

- name: Install and run for the first time
  win_shell: '.\cphalo-{{ halo_package_version }}-win64.exe --% /S /agent-key={{ agent_key }} /grid="https://grid.cloudpassage.com/grid"'
  args:
    chdir: C:\{{ destination_dir }}\

- name: remove installer
  win_shell: erase .\cphalo-4.1.0-win64.exe
  args:
    chdir: C:\{{ destination_dir }}\