---
- name: add CloudPassage repository
  shell: "echo -e '[cloudpassage]\nname=CloudPassage\nbaseurl=https://production.packages.cloudpassage.com/redhat/$basearch\ngpgcheck=1' | sudo tee /etc/yum.repos.d/cloudpassage.repo > /dev/null"

- name: import CloudPassage public key
  command: rpm --import https://production.packages.cloudpassage.com/cloudpassage.packages.key
  become: true
  become_user: root

- name: update yum repositories
  yum:
    update_cache: yes
    state: latest
    name: '*'
  become: true
  become_user: root

- name: Check if Package is installed
  command: rpm -q cphalo
  register: is_installed
  failed_when: false

- name: install the daemon
  package:
    name: cphalo
    state: latest
  become: true
  become_user: root
  when: is_installed.rc > 0

- name: configure agent key
  command: "/opt/cloudpassage/bin/configure --agent-key={{ agent_key }} --grid=https://grid.cloudpassage.com/grid --debug"
  become: true
  become_user: root
  when: is_installed.rc > 0

- name: start the daemon for the first time
  service: name=cphalod state=started
  become: true
  become_user: root
  when: is_installed.rc > 0
